/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SlotMachineRouteImport } from './routes/slot-machine'
import { Route as CrashRouteImport } from './routes/crash'
import { Route as IndexRouteImport } from './routes/index'

const SlotMachineRoute = SlotMachineRouteImport.update({
  id: '/slot-machine',
  path: '/slot-machine',
  getParentRoute: () => rootRouteImport,
} as any)
const CrashRoute = CrashRouteImport.update({
  id: '/crash',
  path: '/crash',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crash': typeof CrashRoute
  '/slot-machine': typeof SlotMachineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crash': typeof CrashRoute
  '/slot-machine': typeof SlotMachineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crash': typeof CrashRoute
  '/slot-machine': typeof SlotMachineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/crash' | '/slot-machine'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/crash' | '/slot-machine'
  id: '__root__' | '/' | '/crash' | '/slot-machine'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrashRoute: typeof CrashRoute
  SlotMachineRoute: typeof SlotMachineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/slot-machine': {
      id: '/slot-machine'
      path: '/slot-machine'
      fullPath: '/slot-machine'
      preLoaderRoute: typeof SlotMachineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crash': {
      id: '/crash'
      path: '/crash'
      fullPath: '/crash'
      preLoaderRoute: typeof CrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrashRoute: CrashRoute,
  SlotMachineRoute: SlotMachineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
